
declare -A DOTFILES_LINKS=(
  [atom/config.cson]="$HOME/.atom/config.cson"
  [bin/cloneall]="$HOME/bin/cloneall"
  [bin/activate-terminal]="$HOME/bin/activate-terminal"
  [bin/format-records]="$HOME/bin/format-records"
  [bin/switch-input-source]="$HOME/bin/switch-input-source"
  [fish/config.fish]="$HOME/.config/fish/config.fish"
  [fish/fishfile]="$HOME/.config/fish/fishfile"
  [fish/functions/....fish]="$HOME/.config/fish/functions/....fish"
  [fish/functions/crackzip.fish]="$HOME/.config/fish/functions/crackzip.fish"
  [fish/functions/mycommits.fish]="$HOME/.config/fish/functions/mycommits.fish"
  [fish/functions/splitOpenVpnFile.fish]="$HOME/.config/fish/functions/splitOpenVpnFile.fish"
  [fish/functions/take.fish]="$HOME/.config/fish/functions/take.fish"
  [fish/functions/fish_title.fish]="$HOME/.config/fish/functions/fish_title.fish"
  [git/.gitconfig]="$HOME/.gitconfig"
  [sublime/Preferences.sublime-settings]="$HOME/.config/sublime-text-3/Packages/User/Preferences.sublime-settings"
  [sublime/Package Control.sublime-settings]="$HOME/.config/sublime-text-3/Packages/User/Package Control.sublime-settings"
  [sublime/Default (Linux).sublime-keymap]="$HOME/.config/sublime-text-3/Packages/User/Default (Linux).sublime-keymap"
)
